### ISSUE TITLE
Mass name squatting on crates.io

### ISSUE THREAD

**Issue by zetanumbers** [oreqizer/rust-notes#1]
Please, if you don't need all those 32 names for your crates, give other people chance. Don't claim everything you could ever come up with.
https://reddit.com/r/rust/comments/mvdttz/recent_crates_on_docsrs/?ref=share&ref_source=link

**Comment by oreqizer** [comment]
ok I will, I thought it's a common, although ugly, practice, so went ahead and reserved some names I came up with. this made me think it's non-regulated on purpose: https://crates.io/policies#squatting

sorry. my account was suspended for the time being. when I will get it back, I will delete everything. I already contacted help@crates.io to do that for me

**Comment by zetanumbers** [comment]
@oreqizer sorry for this crowd, i should have tried to keep this private. I look up new crate updates from time to time. I was a bit disappointed seeing crate titles but nothing of value, so i posted on r/rust looking for someone who knows how to deal with it. Didn't expect to get this much comments tho. I hope i didn't get you to abandon your learning. Again I'm so sorry.

**Comment by oreqizer** [comment]
@ZetaNumbers no problem, you did the right thing! I am actually happy that the community cares so much about this issue. I hope the crates.io team will just help me clean up the mess and unlock my account 🤞

**Comment by oreqizer** [comment]
ok I've been contacted that they deleted those squat crates and that my ban will be elevated in 30 days. that sounds reasonable. I hope I will get to keep at least _one_ of the names I came up with for the HTTP server I wanna do 😄
